---
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: visua-api
    workspace: ../visua-api
  - imageName: visua-frontend
    workspace: ../visua-frontend
deploy:
  kubectl:
    manifests:
    - k8s/*