apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: visua-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: visua-api
          servicePort: 80
      - path: /
        backend:
          serviceName: visua-frontend
          servicePort: 80